### ISSUE TITLE
Using QAF in eclipse, unable to execute the selected test cases as groups

### ISSUE THREAD

**Issue by githubdilip** [qmetry/qaf#115]
Hi Team,

In eclipse, unable to execute test cases as groups based on the meta data we provide in scenarios.
Please do the needful.
Please find below the config file used and scenario file meta data:
Config file:

<?xml version="1.0" encoding="UTF-8"?>
<suite name="CERT1: iOS Smoke Suite" parallel="tests"
	thread-count="1">
	<parameter name="driver.name" value="appiumDriver" />

	<parameter name="appium.additional.capabilities"
		value="{'automationName':'PerfectoMobile','platformName':'iOS','driver.class':'io.appium.java_client.ios.IOSDriver','applicationName':'Beta'}" />

	<parameter name="env.resources" value="resources/qa/ios;resources/users/ios/cert1"></parameter>

	<parameter name="step.provider.pkg"
		value="com.heb.automation.common;com.heb.automation.ios"></parameter>
	<parameter name="wd.command.listeners"
		value="com.heb.automation.common.IOSPerfectoDriverListener"></parameter>
	<parameter name="we.command.listeners"
		value="com.heb.automation.common.IOSWebElementListener"></parameter>

	<parameter name="scenario.file.loc" value="scenarios/test.bdd" />

	<test verbose="2" name="iOS: Browse module">
		<parameter name="driver.capabilities.deviceName" value="XXXXXXXXXX"></parameter>
 		<groups>
			<run>
				<include name="HOT" />
				<include name="COLD" />			
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>

</suite> 

Scenario file:

SCENARIO: Hotuser_Browse_Adding product to list from product finder PDP
META-DATA: {"description":"Hotuser_Browse: Verify choosing the product from the Product Finder and add it to Shopping List in PDP page","groups":["HOT","Add to List","HotUser", "P1"],"TCID":"Browse_TC01","enabled":true}
       
	Given I am a hot user using '${hotuser6.user.email}''${hotuser6.user.password}' with new list added
	When I navigate to Products page
	
END

**Comment by amitbhoraniya** [comment]
As your testng config file and scenario, include/exclude is working from myend, so can you provide more  details what issue/error you are facing?

![image](https://user-images.githubusercontent.com/4617600/26866350-6351d7de-4b7e-11e7-8eb9-34a7d52b2bd9.png)

**Comment by githubdilip** [comment]
Hi Amit,

PFB the console output when I execute with this config file in eclipse
log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.testng.pro.QAFAnnotationTransformer2).
log4j:WARN Please initialize the log4j system properly.
include groups [COLD, HOT]
 exclude groups: [] Scanarios location: scenarios/test.bdd 
[TestNG] Running:
  D:\HEB automation\EclipseNativeApp\config\iOS_Config1.xml

[ThreadUtil] Starting executor timeOut:2147483647ms workers:1 threadPoolSize:1
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.TestHTMLReporter.generateLog(TestHTMLReporter.java:320)
	at org.testng.reporters.TestHTMLReporter.onFinish(TestHTMLReporter.java:40)
	at org.testng.TestRunner.fireEvent(TestRunner.java:1241)
	at org.testng.TestRunner.afterRun(TestRunner.java:1032)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeUtf8File(Utils.java:129)
	at org.testng.reporters.JUnitXMLReporter.generateReport(JUnitXMLReporter.java:185)
	at org.testng.reporters.JUnitXMLReporter.onFinish(JUnitXMLReporter.java:118)
	at org.testng.TestRunner.fireEvent(TestRunner.java:1241)
	at org.testng.TestRunner.afterRun(TestRunner.java:1032)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

===============================================
    iOS: Browse module
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
CERT1: iOS Smoke Suite
Total tests run: 0, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@100d6b1: 0 ms
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateTableOfContents(SuiteHTMLReporter.java:672)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:67)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateSuites(SuiteHTMLReporter.java:735)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:68)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateIndex(SuiteHTMLReporter.java:550)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:69)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateMain(SuiteHTMLReporter.java:564)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:70)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsAndGroups(SuiteHTMLReporter.java:537)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:71)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:358)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:72)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:442)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:72)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:442)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:72)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:442)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:72)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:444)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:72)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:358)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:73)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods-alphabetical.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:442)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:73)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods-alphabetical.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:442)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:73)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods-alphabetical.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:442)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:73)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
ERROR WHILE WRITING TO D:\HEB automation\EclipseNativeApp\test-output\old\CERT1: iOS Smoke Suite\methods-alphabetical.html
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:195)
	at org.testng.internal.Utils.writeFile(Utils.java:179)
	at org.testng.internal.Utils.appendToFile(Utils.java:156)
	at org.testng.reporters.SuiteHTMLReporter.generateMethodsChronologically(SuiteHTMLReporter.java:444)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:73)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateClasses(SuiteHTMLReporter.java:227)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:74)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateReporterOutput(SuiteHTMLReporter.java:209)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:75)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateExcludedMethodsReport(SuiteHTMLReporter.java:191)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:76)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
	at java.io.WinNTFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.testng.internal.Utils.writeFile(Utils.java:177)
	at org.testng.internal.Utils.writeFile(Utils.java:143)
	at org.testng.reporters.SuiteHTMLReporter.generateXmlFile(SuiteHTMLReporter.java:102)
	at org.testng.reporters.SuiteHTMLReporter.generateReport(SuiteHTMLReporter.java:77)
	at org.testng.TestNG.generateReports(TestNG.java:1115)
	at org.testng.TestNG.run(TestNG.java:1074)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
[TestNG] Time taken by org.testng.reporters.jq.Main@4bee09: 40 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@9838eb: 6 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@1ee9989: 8 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@14ba872: 53 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
Preparing For Shut Down...
Preparing For Shut Down...

**Comment by githubdilip** [comment]
When we resolve issues , we see this in console output. No error is observed but the test cases are not considered.

log4j:WARN No appenders could be found for logger (com.qmetry.qaf.automation.testng.pro.QAFAnnotationTransformer2).
log4j:WARN Please initialize the log4j system properly.
include groups [COLD, HOT]
 exclude groups: [] Scanarios location: scenarios/test.bdd 
[TestNG] Running:
  D:\HEB automation\EclipseNativeApp\config\iOS_Config1.xml

[ThreadUtil] Starting executor timeOut:2147483647ms workers:1 threadPoolSize:1

===============================================
    Test1
    Tests run: 0, Failures: 0, Skips: 0
===============================================


===============================================
SmokeSuite
Total tests run: 0, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@100d6b1: 0 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@4bee09: 37 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@9838eb: 5 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@1ee9989: 8 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@14ba872: 25 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 1 ms
Preparing For Shut Down...
Preparing For Shut Down...

**Comment by amitbhoraniya** [comment]
Below is my config file
```
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="QAF Demo" verbose="0">
	<parameter name="scenario.file.loc" value="scenarios/test.bdd" />
	<test verbose="2" name="iOS: Browse module">
		<groups>
			<run>
				<include name="HOT" />
				<include name="COLD" />
			</run>
		</groups>
		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>
</suite>
```
Below is  my `test.bdd` file
```
SCENARIO: Hotuser_Browse_Adding product to list from product finder PDP
META-DATA: {"description":"Hotuser_Browse: Verify choosing the product from the Product Finder and add it to Shopping List in PDP page","groups":["HOT","Add to List","HotUser", "P1"],"TCID":"Browse_TC01","enabled":true}

	Given I am a hot user using '${hotuser6.user.email}''${hotuser6.user.password}' with new list added
	When I navigate to Products page
END
```

And it working as expected, below is my console output, 

```
include groups [COLD, HOT]
 exclude groups: [] Scanarios location: scenarios/test.bdd 
product page
PASSED: Hotuser_Browse_Adding product to list from product finder PDP
        Hotuser_Browse: Verify choosing the product from the Product Finder and add it to Shopping List in PDP page

===============================================
    iOS: Browse module
    Tests run: 1, Failures: 0, Skips: 0
===============================================

[TestNG] Time taken by org.testng.reporters.XMLReporter@2cd2a21f: 19 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@3738449f: 2 ms
[TestNG] Time taken by org.testng.reporters.jq.Main@69997e9d: 16 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 0 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@7ea9e1e2: 0 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@3fb1549b: 15 ms
Preparing For Shut Down...
```
Can you please check from your end what you are missing.

**Comment by githubdilip** [comment]
Hi Amit,

Are you using eclipse version ?, same config file with QAS working fine, But in eclipse the test cases are not considered for execution and Tests run come as '0'. Could you please help in this.

**Comment by githubdilip** [comment]
Any update on this issue ..? @amitbhoraniya  Can you please check once

**Comment by vn01156** [comment]
Any update on this issue ..? Can someone please reply and guide here?

**Comment by cjayswal** [comment]
which version of QAF you are using? You can also try running through ANT or Maven.

**Comment by githubdilip** [comment]
@cjayswal : We are using qaf-2.1.11-RC1-standalone and qaf-support-2.1.10.
If we are not using the groups and execute only with class file, entire bdd file is getting executed. Issue is executing selected groups only. Please do the needful.

<suite name="SmokeSuite" parallel="tests"
	thread-count="1">
	<parameter name="driver.name" value="appiumDriver" />

	<parameter name="appium.additional.capabilities"
		value="{'automationName':'PerfectoMobile','platformName':'iOS','driver.class':'io.appium.java_client.ios.IOSDriver','applicationName':'Beta'}" />

	<parameter name="env.resources" value="resources/qa/ios;resources/users/ios/cert1"></parameter>

	<parameter name="step.provider.pkg"
		value="com.heb.automation.common;com.heb.automation.ios"></parameter>
	<parameter name="wd.command.listeners"
		value="com.heb.automation.common.IOSPerfectoDriverListener"></parameter>
	<parameter name="we.command.listeners"
		value="com.heb.automation.common.IOSWebElementListener"></parameter>

	<parameter name="scenario.file.loc" value="scenarios/test.bdd" />

	<test verbose="2" name="Test1">
		<parameter name="driver.capabilities.deviceName" value="XXX"></parameter>

		<classes>
			<class name="com.qmetry.qaf.automation.step.client.text.BDDTestFactory" />
		</classes>
	</test>

</suite>

**Comment by cjayswal** [comment]
Will you please check with 2.1.11

**Comment by vn01156** [comment]
As suggested we have tried with the 2.1.11 jar. Still getting the same issues and not supporting to execute scenario's using Group names

Note: qaf-2.1.11.jar & qaf-support-2.1.11.jar

**Comment by cjayswal** [comment]
Please post question in [user group](https://groups.google.com/forum/#!forum/qaf-users).
