### ISSUE TITLE
QAF is not compatible with latest selenium version

### ISSUE THREAD

**Issue by amitbhoraniya** [qmetry/qaf#118]
After adding below dependencies, not able to create a driver instance.
```
<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.4.0"/>
<dependency org="org.seleniumhq.selenium" name="selenium-remote-driver" rev="3.4.0"/>
```
Getting below exception
```
java.lang.NoSuchMethodError: org.openqa.selenium.support.ui.FluentWait.withMessage(Lcom/google/common/base/Supplier;)Lorg/openqa/selenium/support/ui/FluentWait;
	at .get 'http://www.google.com'(scenarios/suite1.bdd:6)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:409)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
	at com.qmetry.qaf.automation.step.CommonStep.get_aroundBody24(CommonStep.java:315)
	at com.qmetry.qaf.automation.step.JavaStepReporter.javaTestStep(JavaStepReporter.java:101)
	at com.qmetry.qaf.automation.step.CommonStep.get(CommonStep.java:314)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:160)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:167)
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:219)
```

Earlier in selenium FluentWait class was using `com.google.common.base.Supplier` class.
In latest selenium it changed to `java.util.function.Supplier`.

**Comment by amitbhoraniya** [comment]
Its working below dependency.
```
<dependency org="org.seleniumhq.selenium" name="selenium-support" rev="3.0.0" force="true"/>
<dependency org="org.seleniumhq.selenium" name="selenium-java" rev="3.4.0" force="true"/>
<dependency org="org.seleniumhq.selenium" name="selenium-remote-driver" rev="3.4.0" force="true"/>
```

**Comment by kchuykov** [comment]
@amitbhoraniya , I am getting 'browserName is type object instead of string for IE' and 'browserName was not a boolean' for  firefox 55

**Comment by Raneesh02** [comment]
For me this the dependency set:
<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-support</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>3.14.0</version>
		</dependency>
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-remote-driver</artifactId>
			<version>3.14.0</version>
		</dependency>
		
		<dependency>
			<groupId>io.appium</groupId>
			<artifactId>java-client</artifactId>
			<version>6.1.0</version>
		</dependency>
<dependency>
			<groupId>xmlunit</groupId>
			<artifactId>xmlunit</artifactId>
			<version>1.4</version>
		</dependency>
		
		<dependency>
			<groupId>commons-jxpath</groupId>
			<artifactId>commons-jxpath</artifactId>
			<version>1.3</version>
		</dependency>
		
		<dependency>
			<groupId>org.xmlmatchers</groupId>
			<artifactId>xml-matchers</artifactId>
			<version>1.0-RC1</version>
		</dependency>


    
		<dependency>
			<groupId>com.qmetry</groupId>
			<artifactId>qaf</artifactId>
			<version>${qaf.version}</version>
		</dependency>
		<dependency>
			<groupId>com.qmetry</groupId>
			<artifactId>qaf-support</artifactId>
			<version>${qaf.version}</version>
		</dependency>

**Comment by Raneesh02** [comment]
Its working fine for me.
