### ISSUE TITLE
Unable to launch firefox and IE browsers using QAF2.1.12

### ISSUE THREAD

**Issue by akhiljosephk** [qmetry/qaf#165]
### QAF Version
> 2.1.12 
I am facing this issue with latest Selenium and QAF.

CHROME:
Works fine with Chrome.
The driver session for Chrome is (Example) QAFExtendedWebDriver: chrome on XP (979a57328b5f984cecf90b71689e8970)

IE:
IE opens but doesn't navigate to the URL.
org.openqa.selenium.remote.SessionNotFoundException: session null does not exist
The driver session for IE is QAFExtendedWebDriver: on ANY (null)

Exception:

org.openqa.selenium.remote.SessionNotFoundException: session null does not exist (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 5 milliseconds
Build info: version: '2.53.1', revision: 'a36b8b1cd5757287168e54b817830adce9b0158d', time: '2016-06-30 19:26:09'
System info: host: 'INBAGHPC01201', ip: '10.9.168.96', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_144'
Driver info: com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver
Capabilities [{capabilities={acceptInsecureCerts=false, browserVersion=11, se:ieOptions={nativeEvents=true, browserAttachTimeout=0, ie.ensureCleanSession=false, elementScrollBehavior=0, enablePersistentHover=true, ie.browserCommandLineSwitches=, ie.forceCreateProcessApi=false, requireWindowFocus=false, initialBrowserUrl=http://localhost:1879/, ignoreZoomSetting=false, ie.fileUploadDialogTimeout=3000, ignoreProtectedModeSettings=false}, browserName=internet explorer, pageLoadStrategy=normal, unhandledPromptBehavior=dismiss, platformName=windows, setWindowRect=true}, sessionId=9f2b5a8b-d193-47db-a07f-90ff3cd1fcfa, platform=ANY}]
Session ID: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:678)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:234)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:865)
	at com.quantum.listerners.PerfectoDriverListener.onInitialize(PerfectoDriverListener.java:95)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.onInitialize(QAFExtendedWebDriver.java:338)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.init(QAFExtendedWebDriver.java:153)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.<init>(QAFExtendedWebDriver.java:113)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.getDriver(UiDriverFactory.java:429)
	at com.qmetry.qaf.automation.ui.UiDriverFactory$Browsers.access$6(UiDriverFactory.java:416)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.getDriver(UiDriverFactory.java:228)
	at com.qmetry.qaf.automation.ui.UiDriverFactory.get(UiDriverFactory.java:94)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:511)
	at com.qmetry.qaf.automation.core.QAFTestBase$DriverInitExpectedCondition.apply(QAFTestBase.java:1)
	at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:238)
	at com.qmetry.qaf.automation.core.QAFTestBase.init(QAFTestBase.java:410)
	at com.qmetry.qaf.automation.core.QAFTestBase.getUiDriver(QAFTestBase.java:198)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:47)
	at com.qmetry.qaf.automation.ui.WebDriverTestBase.getDriver(WebDriverTestBase.java:1)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:86)
	at com.qmetry.qaf.automation.ui.AbstractTestPage.<init>(AbstractTestPage.java:93)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:62)
	at com.qmetry.qaf.automation.ui.WebDriverBaseTestPage.<init>(WebDriverBaseTestPage.java:58)

FIREFOX:
Firefox instance opens but doesn't navigate to the URL.
Unable to Create Driver Instance for firefox: Failed to connect to binary FirefoxBinary(C:\Program Files\Mozilla Firefox\firefox.exe)

**Comment by cjayswal** [comment]
Please refer IE driver and Firefox driver documentation. For IE/EDGE/Firefox also you need respective driver and required to set it using system property. With QAF you can set any system property with `system` prefix. For example, `system.webdriver.ie.driver=<path>/iedriverserver.exe` will set system property `webdriver.ie.driver` same for gecko driver. For ie you also need to do some environment set up. 

Closing git issue as it is not qaf bug or feature request. If you need more help post your question or help related topics in [users group](https://groups.google.com/forum/#!forum/qaf-users).
