### ISSUE TITLE
UnreachableBrowserException: Error communicating with the remote browser. It may have died.(Chrome browser)

### ISSUE THREAD

**Issue by meetparag81** [qmetry/qaf#209]
### QAF Version
> Note: only the latest version is supported

### Steps To Reproduce
    1.I am running my testsuite by running testng.xml  and I can see this message. I am using chrome as a browser 
    2.I am using Chrome browser= Version 68.0.3440.84 (Official Build) (64-bit)
    3.My Chrome driver exe is compatible for 67 to 69 build

### Expected behavior
This issue must be resolved

### Actual behavior
More than 100 testcases of 153 is skipped due to this issue
This issue is seen for Tear-down method under @After Method , where driver .quit is initialized.

### Is the issue reproducible on runner?
- [x] Maven

- [x] Eclipse

### Test case sample
@Test(priority=6,enabled=true)
	public void SaveThePatient()
	{
		
		PRP.FillRegistrationForm();
		String Act= PRP.SaveThePatient();
		System.out.println(Act);
		String Exp ="";
	}
@AfterMethod
	public void TearDown()
	{
		driver.quit();
	}

Please refer the stack message 
org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '3.5.3', revision: 'a88d25fe6b', time: '2017-08-29T12:42:44.417Z'
System info: host: 'IVF111', ip: '192.168.1.56', os.name: 'Windows 8.1', os.arch: 'amd64', os.version: '6.3', java.version: '1.8.0_161'
Driver info: driver.version: EventFiringWebDriver
Capabilities [{mobileEmulationEnabled=false, hasTouchScreen=false, platform=WIN8_1, acceptSslCerts=false, goog:chromeOptions={debuggerAddress=localhost:54221}, acceptInsecureCerts=false, webStorageEnabled=true, browserName=chrome, takesScreenshot=true, javascriptEnabled=true, platformName=WIN8_1, setWindowRect=true, unexpectedAlertBehaviour=, applicationCacheEnabled=false, rotatable=false, networkConnectionEnabled=false, chrome={chromedriverVersion=2.41.578737 (49da6702b16031c40d63e5618de03a32ff6c197e), userDataDir=C:\Users\paragb\AppData\Local\Temp\scoped_dir8188_22957}, takesHeapSnapshot=true, unhandledPromptBehavior=, pageLoadStrategy=normal, databaseEnabled=false, handlesAlerts=true, version=68.0.3440.84, browserConnectionEnabled=false, nativeEvents=true, locationContextEnabled=true, cssSelectorsEnabled=true}]
Session ID: 876274fadcd747277de933c7f5b77dde
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:667)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:703)
	at org.openqa.selenium.remote.RemoteWebDriver.quit(RemoteWebDriver.java:542)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.openqa.selenium.support.events.EventFiringWebDriver$2.invoke(EventFiringWebDriver.java:105)
	at com.sun.proxy.$Proxy10.quit(Unknown Source)
	at org.openqa.selenium.support.events.EventFiringWebDriver.quit(EventFiringWebDriver.java:203)
	at com_Milan_Test.WOPUCycyclePageTest.TearDown(WOPUCycyclePageTest.java:252)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:723)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.RuntimeException: Process refused to die after 10 seconds, and couldn't taskkill it: Timeout waiting for process to die
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:133)
	at org.openqa.selenium.os.ProcessUtils.killProcess(ProcessUtils.java:81)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.destroyHarder(UnixProcess.java:265)
	at org.openqa.selenium.os.UnixProcess$SeleniumWatchDog.access$200(UnixProcess.java:219)
	at org.openqa.selenium.os.UnixProcess.destroy(UnixProcess.java:127)
	at org.openqa.selenium.os.CommandLine.destroy(CommandLine.java:153)
	at org.openqa.selenium.remote.service.DriverService.stop(DriverService.java:220)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:94)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:646)
	... 37 more
Caused by: org.openqa.selenium.os.ProcessUtils$ProcessStillAliveException: Timeout waiting for process to die
	at org.openqa.selenium.os.ProcessUtils.waitForProcessDeath(ProcessUtils.java:67)
	at org.openqa.selenium.os.ProcessUtils.killWinProcess(ProcessUtils.java:129)
	... 45 more
Caused by: java.lang.InterruptedException
	at java.lang.ProcessImpl.waitFor(ProcessImpl.java:451)
	at org.openqa.selenium.os.ProcessUtils$ProcessWaiter.run(ProcessUtils.java:154)
	at java.lang.Thread.run(Thread.java:748)

**Comment by cjayswal** [comment]
The exception is from `com_Milan_Test.WOPUCycyclePageTest.TearDown(WOPUCycyclePageTest.java:252)`. You need to make sure that driver session is available!

Why you need tear down or `driver.quite()`? If you are using qaf, you can take benefit of driver management from qaf. For example, if you want to have new driver session for each test case you can set `selenium.singletone=methods`. You can refer [properties list](https://qmetry.github.io/qaf/latest/properties_list.html) for other useful properties.

For more help, support and queries, you can post in [users-group](https://groups.google.com/forum/#!forum/qaf-users)

**Comment by meetparag81** [comment]
@ cjayswal , I am not using qaf, Any other solution, because I can see the script works correctly on chrome build 65, but failing on 68 build and I couldn't stop auto updates of chrome.

**Comment by meetparag81** [comment]
I stopped the updates still issue is seen, I can see this isse on Version 65.0.3325.162 (Official Build) (32-bit) and version 68.

**Comment by cjayswal** [comment]
For further queries or question post in [qaf users group](https://groups.google.com/forum/#!forum/qaf-users) or [stackoverflow with qaf tag](http://stackoverflow.com/questions/tagged/qaf) or [chromedriver-users](https://groups.google.com/forum/#!forum/chromedriver-users)
