### ISSUE TITLE
Test Cases are skipped with 2.1.14 jar files due to java.lang.IllegalStateException: Infinite loop in property interpolation

### ISSUE THREAD

**Issue by Priya335021** [qmetry/qaf#274]
### QAF Version
> Note: only the latest version is supported
2.1.14
### Steps To Reproduce
    1. Updated the jar file version to 2.1.14
    2. Executed a test case which uses excel data provider
    

### Expected behavior
The same test case could be executed perfectly with version 2.1.13. The same way of execution is expected with 2.1.14 version

### Actual behavior
Getting exception as below.
java.lang.IllegalStateException: Infinite loop in property interpolation of {"lineNo":19,"sheetName":"RCCA","Groups":["RCCA","TC_862"],"name":"Verify Local Admin creates parent RCCA record","sign":"scenarios.iQMS.RCCA.bdd.Verify Local Admin creates parent RCCA record( java.util.Map)[pri:1000, instance:com.qmetry.qaf.automation.step.client.DataDrivenScenario@3e8]","description":"Verify Local Admin creates parent RCCA record","referece":"scenarios/iQMS/RCCA.bdd","dataFile":"${dataFile}","key":"TC_862"}: dataFile

### Is the issue reproducible on runner?

- [ ] QAS
- [x] Maven
- [ ] Gradle
- [ ] Ant
- [x] Eclipse

### Test case sample
Test case with meta-data:
SCENARIO: Verify Local Admin creates parent RCCA record
META-DATA: {"description":"Verify Local Admin creates parent RCCA record","Groups":["RCCA","TC_862"], "dataFile":"${dataFile}", "sheetName":"RCCA","key":"TC_862"}

dataFile parameter and its value are given in xml file during execution.

**Comment by cjayswal** [comment]
This is because `dataFile` is meta-key and meta-key is available for parameter resolution resolution. You are assigning `dataFile` parameter to itself and that's why it's Infinite loop. Change the parameter name to something else. For example:
`"dataFile":"${adminTestData}"` or  `"dataFile":"resources/${env}/dataFile.xls"`
```
META-DATA: {"description":"Verify Local Admin creates parent RCCA record","Groups":["RCCA","TC_862"], "dataFile":"${adminTestData}", "sheetName":"RCCA","key":"TC_862"}

```

**Comment by Priya335021** [comment]
Yes, it is working fine with the different parameter name. Thanks for your help.
But when I execute a testNG method from config file it throws an exception as "No data provider found". The data provider is not used in the test method. It was working fine with 2.1.13 jar files. Getting this exception only in 2.1.14 jar files.

TestNG xml:
<suite name="Regression Suite" verbose="2">

<parameter name="ExecutorFile" value="config\\executor\\TestCases_Executor" />
	<test name="Notifications" enabled="true">
		<classes>
			<class name="com.automation.ReusableUtils.testCaseExecutor" />
		</classes>
	</test>
</suite>

Test method:

@Test
	@Parameters("ExecutorFile")
	public static void testMethod(String ExecutorFile) throws Exception {
	// implementation
         }

Error log:
[Error] java.lang.RuntimeException: No data provider found
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.getData(QAFInetrceptableDataProvider.java:332)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.interceptedDataProvider(QAFInetrceptableDataProvider.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:111)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:781)
	at org.testng.TestRunner.run(TestRunner.java:635)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by Priya335021** [comment]
TestNG XML:
<suite name="Regression Suite" verbose="2">

<parameter name="ExecutorFile" value="config\\executor\\TestCases_Executor" />
	<test name="Notifications" enabled="true">
		<classes>
			<class name="com.automation.lam.ReusableUtils.testCaseExecutor" />
		</classes>
	</test>
</suite>

**Comment by Priya335021** [comment]
XML:
<parameter name="ExecutorFile" value="config\\executor\\TestCases_Executor" />

**Comment by Priya335021** [comment]
xml:

> <parameter name="ExecutorFile" value="config\\executor\\TestCases_Executor" />

**Comment by cjayswal** [comment]
Closing this as "RuntimeException: No data provider found" has no relation to original issue. Refer #278 for RuntimeException: No data provider found.
