### ISSUE TITLE
java.util.regex.PatternSyntaxException: Unmatched closing ')' when using () in step description with escape charctor

### ISSUE THREAD

**Issue by cjayswal** [qmetry/qaf#320]
### QAF Version
> 3.0.0-beta-1
QAF-cucumber version 3.0.0-beta-1

### Steps To Reproduce
    
1. Create step def using cucumber5 with expression `@Given("I have {int} item\\(s)")`
2. Call step in BDD as `Given I have 5 item(s)`
3. Run as TestNG test

### Expected behavior
Should call the step and work properly

### Actual behavior
Automation error:

```
    java.util.regex.PatternSyntaxException: Unmatched closing ')' near index 145
    (((^(Given|When|Then|And|Using|Having|With))\s)?I have ((\{.*})|(\[.*])|('([^\\']|\\\\|\\')*')|("([^\\"]|\\\\|\\")*")|([-+]?\d+(\.\d+)?)) item\(s))
                                                                                                                                                     ^
    	at java.util.regex.Pattern.error(Pattern.java:1955)
    	at java.util.regex.Pattern.compile(Pattern.java:1700)
    	at java.util.regex.Pattern.(Pattern.java:1351)
    	at java.util.regex.Pattern.compile(Pattern.java:1054)
    	at com.qmetry.qaf.automation.util.StringMatcher$LikeIgnoringCase.match(StringMatcher.java:257)
    	at com.qmetry.qaf.automation.step.client.text.BDDDefinitionHelper.matches(BDDDefinitionHelper.java:249)
    	at com.qmetry.qaf.automation.step.BDDStepMatcherFactory$DefaultBDDStepMatcher.matches(BDDStepMatcherFactory.java:55)
    	at com.qmetry.qaf.automation.step.StringTestStep.getTestStep(StringTestStep.java:188)
    	at com.qmetry.qaf.automation.step.StringTestStep.initStep(StringTestStep.java:70)
    	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:205)
    	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237)
    	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    	at java.lang.reflect.Method.invoke(Method.java:498)
    	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
    	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
    	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
    	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
    	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
    	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
    	at org.testng.TestRunner.privateRun(TestRunner.java:778)
    	at org.testng.TestRunner.run(TestRunner.java:632)
    	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
    	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
    	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
    	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
    	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
    	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
    	at org.testng.TestNG.runSuites(TestNG.java:1133)
    	at org.testng.TestNG.run(TestNG.java:1104)
    	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
    	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
    	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

```

**Comment by cjayswal** [comment]
Works fine with QAF-cucumeber when running using cucumber runner. Issue is only when running as TestNG test.
