### ISSUE TITLE
Json file contains ":" in content would get JsonSyntaxException

### ISSUE THREAD

**Issue by MoonLikeSinging** [qmetry/qaf#340]
### QAF Version
> 2.1.14

### Steps To Reproduce
    1.  Use above test data in feature as test file

### Expected behavior
I can get the content in test successfully.

### Actual behavior
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 67 path $.[2]

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> ###Test Data
[
  {
    "waitTimeToReceiveEmail": "5",
    "emailContent" : {
      "sender" : "test@test.com",
      "title": "test",
      "content" : ["休假申请已被批准", "业务流程：短期休假申请:moon"]
    }
  }
]
>### Feature file
    Then User can validate email content with "<emailContent>"
    Examples: {'datafile':'./src/main/resources/data/test.json'}

### Note:
I use Gson to get the content, it's worked well.
JsonParser.parseReader(new FileReader("test.json"))

**Comment by MoonLikeSinging** [comment]
It doesn't work to add backslash to escape like this :
"content" : ["休假申请已被批准", "业务流程：短期休假申请\\:moon"]

**Comment by cjayswal** [comment]
Can you provide detailed exception stacktrace?

**Comment by MoonLikeSinging** [comment]
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 67 path $.[2]

	at .Then User can validate email content with "${emailContent}"(src/main/resources/scenarios/poa/EmailValidation.feature:11)
	at com.google.gson.Gson.fromJson(Gson.java:947)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.quantum.listeners.QuantumReportiumListener.getProcessStepDescription(QuantumReportiumListener.java:610)
	at com.quantum.listeners.QuantumReportiumListener.beforExecute(QuantumReportiumListener.java:249)
	at com.qmetry.qaf.automation.step.BaseTestStep.beforExecute(BaseTestStep.java:180)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:146)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:180)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:69)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.google.gson.stream.MalformedJsonException: Unterminated array at line 1 column 67 path $.[2]
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:477)
	at com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
	at com.google.gson.internal.bind.ObjectTypeAdapter.read(ObjectTypeAdapter.java:60)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)
	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at com.google.gson.Gson.fromJson(Gson.java:817)
	at com.quantum.listeners.QuantumReportiumListener.getProcessStepDescription(QuantumReportiumListener.java:610)
	at com.quantum.listeners.QuantumReportiumListener.beforExecute(QuantumReportiumListener.java:249)
	at com.qmetry.qaf.automation.step.BaseTestStep.beforExecute(BaseTestStep.java:180)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:146)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:134)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:180)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:781)
	at org.testng.TestRunner.run(TestRunner.java:635)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	... 4 more

**Comment by cjayswal** [comment]
I tried with latest version `3.0.0-RC3` and worked fine for me. Test executed without any error, able to print `content` column value in console and also i am able to see following test-data in qaf report:

Test Data:
[ { "waitTimeToReceiveEmail": "5", "emailContent": { "sender": "test@test.com", "title": "test", "content": [ "休假申请已被批准", "业务流程：短期休假申请:moon" ] }, "__index": 1 } ]

**Comment by MoonLikeSinging** [comment]
@cjayswal  ok, let me update the framework and try it.

**Comment by cjayswal** [comment]
@MoonLikeSinging, I did try to reproduce with latest version and found working without any issue. Please try with latest version and if you are facing issue with latest then provide step to reproduce with latest version.

**Comment by MoonLikeSinging** [comment]
@cjayswal sorry, after retest, this bug is not a qaf bug, it's worked well on version 2.14 and 2.15, and this should cause by perfecto team's perfecto-quantum which integrated with qaf.
