### ISSUE TITLE
javascript error: end is not defined

### ISSUE THREAD

**Issue by C5257429** [qmetry/qaf#364]
### QAF Version
>2.1.15

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
org.openqa.selenium.JavascriptException: javascript error: end is not defined
  (Session info: chrome=89.0.4389.114)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MSI', ip: '192.168.0.109', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_271'
Driver info: com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.114, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: C:\Users\91974\AppData\Loca...}, goog:chromeOptions: {debuggerAddress: localhost:51762}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 8a68183d94c9722dd1f1d6f5bb32fa39
14:10:14:638: Executing quit parameters: {} 
14:10:14:638: Executing executeScript parameters: {"args":[{}],"script":"mobile:execution:close"} 
	at sun.reflect.GeneratedConstructorAccessor26.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:233)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.executeScript(QAFExtendedWebDriver.java:571)
	at com.perfecto.reportium.client.PerfectoReportiumClient.executeScript(PerfectoReportiumClient.java:228)
	at com.perfecto.reportium.client.PerfectoReportiumClient.testStop(PerfectoReportiumClient.java:198)
	at com.perfecto.reportium.client.PerfectoReportiumClient.testStop(PerfectoReportiumClient.java:175)
	at com.quantum.listeners.QuantumReportiumListener.onTestSuccess(QuantumReportiumListener.java:331)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1720)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:703)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by C5257429** [comment]
executing scripts but each time this error msg also coming in to console

**Comment by cjayswal** [comment]
Please, share the test case (as small as possible) which reproduces the issue

**Comment by Ravi21487** [comment]
Hi,
i just install quantum starter kit project unzip that zip file import in to eclipse just i ran testng_all.xml file i seen this error 

i tried jdk 11 and 1.8 also  i m getting each time this error when run config file.


MAC  89.0.4389.114]: █▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀█
[MAC  89.0.4389.114]: █ TEST STARTED: Search Quantum █
[MAC  89.0.4389.114]: █▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄█
org.openqa.selenium.JavascriptException: javascript error: start is not defined
  (Session info: chrome=89.0.4389.114)
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: '192.168.0.106', ip: 'fe80:0:0:0:c9c:64b3:4e6e:7bbb%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '11.0.10'
Driver info: com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver
Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 89.0.4389.114, chrome: {chromedriverVersion: 89.0.4389.23 (61b08ee2c5002..., userDataDir: /var/folders/cd/3n83nn9j5qq...}, goog:chromeOptions: {debuggerAddress: localhost:54748}, javascriptEnabled: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: MAC, platformName: MAC, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: e140e085d21bd99eed75ea321fd10c25
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.createException(W3CHttpResponseCodec.java:187)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:122)
	at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.execute(QAFExtendedWebDriver.java:233)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebDriver.executeScript(QAFExtendedWebDriver.java:571)
	at com.perfecto.reportium.client.PerfectoReportiumClient.executeScript(PerfectoReportiumClient.java:228)
	at com.perfecto.reportium.client.PerfectoReportiumClient.testStart(PerfectoReportiumClient.java:120)
	at com.quantum.listeners.QuantumReportiumListener.onTestStart(QuantumReportiumListener.java:242)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1724)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1699)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:622)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
12:05:44:004: 

Executing scenario: Search Quantum -  
12:05:44:017: pkg: com.qmetry.qaf.automation.step 
**Unable to get class com.qmetry.qaf.automation.step.client.TestStepExporter from jar /Users/mallikarjunaravi/.m2/repository/com/qmetry/qaf/2.1.15/qaf-2.1.15.jar**
12:05:44:560: pkg: com.quantum.steps 
12:05:44:692: Invoking Teststep: Given I am on Google Search Page 
[MAC  89.0.4389.114]: ▄ ▄ ▄ BEGIN STEP: Given I am on Google Search Page ▄ ▄ ▄

**Comment by cjayswal** [comment]
This looks error is from Quantum listener, will you connect to the respective team?

**Comment by cjayswal** [comment]
Closing inactive issue
