### ISSUE TITLE
com.qmetry.qaf.automation.testng.DataProviderException Data-provider: &apos;scenarios&apos; not found in class: &apos;io.cucumber.testng.AbstractTestNGCucumberTests&apos;. Please provide valid data provider name as dataProvider

### ISSUE THREAD

**Issue by rajkirantuduru** [qmetry/qaf#377]
### QAF Version
> Note: only the latest version is supported
[RemoteTestNG] detected TestNG version 6.10.0
[TestNGContentHandler] [WARN] It is strongly recommended to add "<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd" >" at the top of your file, otherwise TestNG may fail or not work as expected.
log4j:WARN No such property [follow] in org.apache.log4j.FileAppender.
Added "QAFMethodSelector"
java.lang.NoSuchFieldException: modifiers
	at java.base/java.lang.Class.getDeclaredField(Class.java:2549)
	at com.qmetry.qaf.automation.util.ClassUtil.setField(ClassUtil.java:599)
	at com.qmetry.qaf.automation.testng.pro.QAFExecutionListener.<init>(QAFExecutionListener.java:52)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:780)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:722)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1393)
	at org.testng.TestNG.addServiceLoaderListeners(TestNG.java:1017)
	at org.testng.TestNG.initializeConfiguration(TestNG.java:966)
	at org.testng.TestNG.run(TestNG.java:1089)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
[ConfigurationManager] - ISFW build info: {qaf-Type=core, qaf-Revision=0, qaf-Build-Time=26-Jul-2020 22:16:34, qaf-Version=3.0}
[ConfigurationManager] - Resource dir: C:\Users\rtuduru\git\qaf-blank-project-maven\resources. Found property files to load: 6
[ConfigurationManager] - Resource dir: C:\Users\rtuduru\git\qaf-blank-project-maven\resources. Found property files to load: 0
[TestNG] Running:
  C:\Users\rtuduru\AppData\Local\Temp\testng-eclipse-556683797\testng-customsuite.xml

[Error] com.qmetry.qaf.automation.testng.DataProviderException: Data-provider: &apos;scenarios&apos; not found in class: &apos;io.cucumber.testng.AbstractTestNGCucumberTests&apos;. Please provide valid data provider name as dataProvider
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.getDataProviderMethod(QAFInetrceptableDataProvider.java:372)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.invokeCustomDataProvider(QAFInetrceptableDataProvider.java:345)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.interceptedDataProvider(QAFInetrceptableDataProvider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:111)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

[32m[1m?????????????????????????????????????????????????????????????????????????????????????[0m
[32m[1m?[0m Share your Cucumber Report with your team at [36m[1m[4mhttps://reports.cucumber.io[0m          [32m[1m?[0m
[32m[1m?[0m Activate publishing with one of the following:                                    [32m[1m?[0m
[32m[1m?[0m                                                                                   [32m[1m?[0m
[32m[1m?[0m src/test/resources/cucumber.properties:          [36mcucumber.publish.enabled[0m=[36mtrue[0m    [32m[1m?[0m
[32m[1m?[0m src/test/resources/junit-platform.properties:    [36mcucumber.publish.enabled[0m=[36mtrue[0m    [32m[1m?[0m
[32m[1m?[0m Environment variable:                            [36mCUCUMBER_PUBLISH_ENABLED[0m=[36mtrue[0m    [32m[1m?[0m
[32m[1m?[0m JUnit:                                           [36m@CucumberOptions[0m(publish = [36mtrue[0m) [32m[1m?[0m
[32m[1m?[0m                                                                                   [32m[1m?[0m
[32m[1m?[0m More information at [36mhttps://cucumber.io/docs/cucumber/environment-variables/[0m      [32m[1m?[0m
[32m[1m?[0m                                                                                   [32m[1m?[0m
[32m[1m?[0m Disable this message with one of the following:                                   [32m[1m?[0m
[32m[1m?[0m                                                                                   [32m[1m?[0m
[32m[1m?[0m src/test/resources/cucumber.properties:          [36mcucumber.publish.quiet[0m=[36mtrue[0m      [32m[1m?[0m
[32m[1m?[0m src/test/resources/junit-platform.properties:    [36mcucumber.publish.quiet[0m=[36mtrue[0m      [32m[1m?[0m
[32m[1m?????????????????????????????????????????????????????????????????????????????????????[0m
SKIPPED: runScenario
         Runs Cucumber Scenarios
java.lang.RuntimeException: com.qmetry.qaf.automation.testng.DataProviderException: Data-provider: 'scenarios' not found in class: 'io.cucumber.testng.AbstractTestNGCucumberTests'. Please provide valid data provider name as dataProvider
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:111)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:509)
	at org.testng.internal.Invoker.handleParameters(Invoker.java:1293)
	at org.testng.internal.Invoker.createParameters(Invoker.java:1020)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1110)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:778)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: com.qmetry.qaf.automation.testng.DataProviderException: Data-provider: 'scenarios' not found in class: 'io.cucumber.testng.AbstractTestNGCucumberTests'. Please provide valid data provider name as dataProvider
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.getDataProviderMethod(QAFInetrceptableDataProvider.java:372)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.invokeCustomDataProvider(QAFInetrceptableDataProvider.java:345)
	at com.qmetry.qaf.automation.testng.dataprovider.QAFInetrceptableDataProvider.interceptedDataProvider(QAFInetrceptableDataProvider.java:112)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:55)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	... 22 more

===============================================
    Default test
    Tests run: 1, Failures: 0, Skips: 1
===============================================

===============================================
Default suite
Total tests run: 1, Failures: 0, Skips: 1
===============================================

[TestNG] Time taken by org.testng.reporters.jq.Main@81ff872: 386 ms
[TestNG] Time taken by [FailedReporter passed=0 failed=0 skipped=0]: 60 ms
[TestNG] Time taken by org.testng.reporters.JUnitReportReporter@6813a331: 34 ms
[TestNG] Time taken by org.testng.reporters.EmailableReporter2@5649ec46: 49 ms
[TestNG] Time taken by org.testng.reporters.SuiteHTMLReporter@55120f99: 387 ms
[TestNG] Time taken by org.testng.reporters.XMLReporter@3cc20577: 50 ms
Preparing For Shut Down...

### Steps To Reproduce
    1.
    2.
    3.

### Expected behavior
It should execute the runner file

### Actual behavior
Facing Data Provider exception 
<img width="392" alt="TestRunner file" src="https://user-images.githubusercontent.com/23114596/129402880-35985bae-e2e0-4d39-bf40-1e282211b991.PNG">
com.qmetry.qaf.automation.testng.DataProviderException

Hi Chirag,

While cucumber testng runner file I am facing No Data Provider found Exception .I dont have data provider in runner file still I am facing issue.can you please look into this once and help me once

Note:I am attaching my  testng runner file and POM.xml file

### Is the issue reproducible on runner?
yes it is reproducible on runner file
- [x] QAS
- [ ] Maven--Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue

**Comment by cjayswal** [comment]
Try with cucumber cli or junit or use [qaf bdd runner](https://github.com/qmetry/qaf-cucumber#using-qaf-cucumber-with-qaf-bdd-runner)
