### ISSUE TITLE
NoSuchMethodError when using CommonStep

### ISSUE THREAD

**Issue by dscholtz-lab49** [qmetry/qaf#459]
### QAF Version 4.0.0-RC3
> Note: If I use the locator.click() it works fine, it only happen if I try to use the CommonStep methods

### Steps To Reproduce
    1. Use any of the CommonStep method e.g. click(locator)
    2.
    3.

### Expected behavior
It should click on element

### Actual behavior
it fails with the following error
java.lang.NoSuchMethodError: 'com.qmetry.qaf.automation.step.JavaStepReporter com.qmetry.qaf.automation.step.JavaStepReporter.aspectOf()'
	at .Then the button "conventional.language" is clicked(src/test/resources/scenarios/web/Onboarding.feature:14)
	at com.qmetry.qaf.automation.step.CommonStep.click(CommonStep.java:454)
	at com.qa.steps.web.WebStepDefinitions.theButtonIsClicked(WebStepDefinitions.java:42)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:128)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174)
	at com.qmetry.qaf.automation.step.client.Scenario.scenario(Scenario.java:237)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

### Is the issue reproducible on runner?

- [ ] QAS
- [ ] Maven
- [x] Gradle
- [ ] Ant
- [ ] Eclipse

### Test case sample
> Please, share the test case (as small as possible) which shows the issue
    @QAFTestStep(description="the input field {0} is filled with {1}", stepName = "input is filled")
    public void theInputIsFilled(String locator, String text) {
        sendKeys(text, locator);
    }

**Comment by dscholtz-lab49** [comment]
Fixed the issue creating an aspectj aop.xml config file under META-INF. It can be empty, just need to exist
