### ISSUE TITLE
Caused by: java.lang.ClassCastException: class io.appium.java_client.android.AndroidDriver cannot be cast to class com.qmetry.qaf.automation.ui.webdriver.FindsByCustomStretegy (io.appium.java_client.android.AndroidDriver and com.qmetry.qaf.automation.ui.webdriver.FindsByCustomStretegy are in unnamed module of loader 'app') 	

### ISSUE THREAD

**Issue by RaviMv08** [qmetry/qaf#460]
### QAF Version
> 3.2.0

### Steps To Reproduce
    1.  after upgrading quantum 1.31.0 
    2.
    3.

### Is the issue reproducible on runner?

- [x] QAS
- [ ] Maven
- [ ] Gradle
- [x] Ant
- [ ] Eclipse

### Test case sample
>org.openqa.selenium.TimeoutException: Timed out after 7 seconds: Wait time out for Using accessibility id: Account Menu to be visible
Build info: version: '4.8.3', revision: 'e5e76298c3'
System info: os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.16', java.version: '12.0.2'
Driver info: driver.version: unknown
	at com.qmetry.qaf.automation.ui.util.DynamicWait.until(DynamicWait.java:168)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.waitForVisible(QAFExtendedWebElement.java:558)
	at com.quantum.pages.HomePage.testAccessibilityId(xxxxx.java:39)
	at com.quantum.pages.HomePage.iVerifyProfileIcon(xxxxxx.java:46)
	at com.quantum.pages.HomePage.iTapProfileIcon(xxxxxx.java:54)
	at com.quantum.steps.HomePageStepsDefs.iTapProfileIcon(xxxxxxxStepsDefs.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at com.qmetry.qaf.automation.step.JavaStep.doExecute(JavaStep.java:150)
	at com.qmetry.qaf.automation.step.BaseTestStep.execute(BaseTestStep.java:149)
	at com.qmetry.qaf.automation.step.StringTestStep.execute(StringTestStep.java:128)
	at com.qmetry.qaf.automation.step.client.Scenario.execute(Scenario.java:174)
	at com.qmetry.qaf.automation.step.client.DataDrivenScenario.scenario(DataDrivenScenario.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.testng.TestRunner.privateRun(TestRunner.java:833)
	at org.testng.TestRunner.run(TestRunner.java:606)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:475)
	at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.ClassCastException: class io.appium.java_client.android.AndroidDriver cannot be cast to class com.qmetry.qaf.automation.ui.webdriver.FindsByCustomStretegy (io.appium.java_client.android.AndroidDriver and com.qmetry.qaf.automation.ui.webdriver.FindsByCustomStretegy are in unnamed module of loader 'app')
	at com.qmetry.qaf.automation.ui.webdriver.ByCustom$1.findElements(ByCustom.java:81)
	at org.openqa.selenium.remote.ElementLocation$ElementFinder$1.findElements(ElementLocation.java:146)
	at org.openqa.selenium.remote.ElementLocation.findElements(ElementLocation.java:121)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:367)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:359)
	at com.qmetry.qaf.automation.ui.webdriver.QAFExtendedWebElement.isPresent(QAFExtendedWebElement.java:372)
	at com.qmetry.qaf.automation.ui.util.QAFWebElementExpectedConditions$1.apply(QAFWebElementExpectedConditions.java:49)
	at com.qmetry.qaf.automation.ui.util.QAFWebElementExpectedConditions$1.apply(QAFWebElementExpectedConditions.java:45)
	at com.qmetry.qaf.automation.ui.util.DynamicWait.until(DynamicWait.java:147)
	... 36 more

**Comment by RaviMv08** [comment]
any update on this issue?
